In [ ]:
s=('hello')
print(s)

hello


In [ ]:
#2. string manipulation
s="hello"
print (s)
#print (s[0],s[1],s[-1],s[-2], len (s))
# negative indicates loop starting from end as -1
#print(s[0],s[1],s[2],s[3],s[4])
#print (s[0],s[-1],s[-2])
#print (s[5])
print (s+ " world")
print (s + " world" + " nida")

hello
hello world
hello world nida


In [ ]:
#3. string is immutable
s='hello'
print(s)
type(s)

s[1]= 'b'
#it wouldnt work

hello


TypeError: ignored

In [ ]:
#4. strings and integer
s='hello'
print(s)
num=10
print(num)
#print (s+num) #gives error
print (s + str(num)) #gives error if previous line is not added as comment

hello
10
hello10


In [ ]:
#5. string methods
s=" HelloNIda "
print(s.lower())
print(s.upper())
print(s.strip())
print(s.isalpha())
print(s.isdigit())
print(s.isspace())


 hellonida 
 HELLONIDA 
HelloNIda
False
False
False


In [ ]:
s="Hello"
print(s[1:3])
print('\n')

print(s[1:])
print('\n')

print(s[-4:3])

el


ello


el


In [ ]:
#strings old way of printing
str1='hello %s, %d' %('world',10)
print(str1)

hello world, 10


In [ ]:
#new style
str2='Hello{}, {}'.format('world',10)
print(str2)

str3='Hello {wd}, {num}'.format(num=10, wd='World')
print(str3)

str4= 'Hello {wd:10}, {num:.3f}'.format(num=10.0, wd='World')
print(str4)

Helloworld, 10
Hello World, 10
Hello World     , 10.000


In [ ]:
#if statement
num=3
print(num)
if num < 5:
  print('num is smaller than 5')

if num > 5:
  print ('num is greater than 5')
elif num== 5 :
  print('num is 5')
else:
  print ('num is smaller than 5')

3
num is smaller than 5
num is smaller than 5


In [ ]:
#Function calls
print (type(32))
type(32)
print(int(32))

#int('hello')
print (int (-2.3))

import math
print(math.sin(3.1416))
print(math.cos(3.1416))
print(math.tan(3.1416))
print(math.asin(0))
print(math.acos(0))
print(math.atan(0))
print(math.sqrt(4))


help('math') #similar to manual in bash
print(math.copysign(1,-2))
print(math.degrees(3.14))
print(math.floor(-3.45))
print(math.radians(90))

<class 'int'>
32
-2
-7.346410206643587e-06
-0.9999999999730151
7.346410206841829e-06
0.0
1.5707963267948966
0.0
2.0
Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Re

In [ ]:
#define functions
def print_name():
  print("Iam Nida")
  print("Ïam always blah blah")

print_name()

Iam Nida
Ïam always blah blah


In [ ]:
#function parameters and arguments
def print_twice(arg1) :
  print(arg1)
  print(arg1)



print_twice(math.pi)
print_twice('Spam'*4)

3.141592653589793
3.141592653589793
SpamSpamSpamSpam
SpamSpamSpamSpam


In [ ]:
#function returns
def print_twice(arg1):
  print(arg1)
  print(arg1)
result= print_twice('Bing')
print(result)

Bing
Bing
None


In [ ]:
#function returns
def print_twice(arg1,arg2):
  return(arg1,arg2)
  #return (arg1,arg2) *2

result1,result2 = print_twice('Bing', 'Nida')
print(result1)
print(result2)

Bing
Nida


In [ ]:
#function checking type of arguments- recursive
def factorial(n):
  if not isinstance(n, int):
    print( "factorial is only defined for integers")
    return None
  elif n < 0 :
    print ("factorial is not defined for negative numbers")
    return None
  elif n == 0 :
    return 1
  else :
    return n*factorial(n-1)

factorial (-3.14)

factorial is only defined for integers


In [ ]:
#default arguments/ function overloading
def func1(arg1, arg2=None):
  if arg2 is None:
    print(arg1)
  else:
    print(arg1,arg2)

func1('hello')

func1('hello' , 'world')

hello
hello world


In [ ]:
from math import pi
print (pi)

3.141592653589793


In [ ]:
#global / local variables
global_var = 1

def func1():
  global_var = 2
  print ("ït is set to 2")
func1()
global_var

ït is set to 2


1

In [ ]:
#global / local variables
global_var = 1

def func2():
  global global_var
  global_var = 2
func2()
global_var

2

In [ ]:
#example1
import math

a=2;
b=5;
c=(a**2+b**2)**(0.5);
d=math.sqrt(c)

x= c/d;
y=c*d;
z= a* math.sin(b)
print('Hypo c=',c)
print('sq root d=',d)
print('quotient=',x)
print('product=',y)
print('sine is',z)

e=math.log(d)
print(d)
p= math.factorial(d)
print (p)


Hypo c= 5.385164807134504
sq root d= 2.320595787106084
quotient= 2.3205957871060834
product= 12.496790764308276
sine is -1.917848549326277
2.320595787106084


TypeError: ignored

In [ ]:
from os import MFD_HUGE_1GB
from scipy import *
from numpy import *

M1=array([[1,2,3],[3,4,5],[1,2,1]])
M2=array([[0,1,2],[3,4,5],[7,8,2]])

M3= M1*M2
M4= 2*M1
import numpy
print('\n M1=',M1)
print('\n M2=',M2)
print('\n M3=',M3)
print('\n M4=',M4)
print(numpy.linalg.inv(M3))
print(M3.T)


 M1= [[1 2 3]
 [3 4 5]
 [1 2 1]]

 M2= [[0 1 2]
 [3 4 5]
 [7 8 2]]

 M3= [[ 0  2  6]
 [ 9 16 25]
 [ 7 16  2]]

 M4= [[ 2  4  6]
 [ 6  8 10]
 [ 2  4  2]]
[[-0.72727273  0.18181818 -0.09090909]
 [ 0.31027668 -0.08300395  0.10671937]
 [ 0.06324111  0.02766798 -0.03557312]]
[[ 0  9  7]
 [ 2 16 16]
 [ 6 25  2]]
